In [2]:
import numpy as np

In [6]:
sample=np.arange(1,21)
sample

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [7]:
sample+(2*sample)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60])

In [8]:
np.exp(sample)

array([  2.71828183e+00,   7.38905610e+00,   2.00855369e+01,
         5.45981500e+01,   1.48413159e+02,   4.03428793e+02,
         1.09663316e+03,   2.98095799e+03,   8.10308393e+03,
         2.20264658e+04,   5.98741417e+04,   1.62754791e+05,
         4.42413392e+05,   1.20260428e+06,   3.26901737e+06,
         8.88611052e+06,   2.41549528e+07,   6.56599691e+07,
         1.78482301e+08,   4.85165195e+08])

In [11]:
np.sqrt(sample)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
        2.44948974,  2.64575131,  2.82842712,  3.        ,  3.16227766,
        3.31662479,  3.46410162,  3.60555128,  3.74165739,  3.87298335,
        4.        ,  4.12310563,  4.24264069,  4.35889894,  4.47213595])

In [12]:
np.log(sample)

array([ 0.        ,  0.69314718,  1.09861229,  1.38629436,  1.60943791,
        1.79175947,  1.94591015,  2.07944154,  2.19722458,  2.30258509,
        2.39789527,  2.48490665,  2.56494936,  2.63905733,  2.7080502 ,
        2.77258872,  2.83321334,  2.89037176,  2.94443898,  2.99573227])

In [13]:
np.max(sample)

20

In [14]:
np.min(sample)

1

In [21]:
sample=np.append(sample,100) # if we dont write sample= then it will not update the sample
sample

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20, 100, 100])

In [22]:
np.max(sample)

100

In [23]:
np.argmax(sample) #gives index of maximum value

20

In [24]:
np.argmin(sample)

0

In [25]:
np.square(sample)

array([    1,     4,     9,    16,    25,    36,    49,    64,    81,
         100,   121,   144,   169,   196,   225,   256,   289,   324,
         361,   400, 10000, 10000], dtype=int32)

In [26]:
np.std(sample)

26.310290856595973

In [27]:
np.var(sample)

692.23140495867767

In [28]:
np.mean(sample)

18.636363636363637

In [35]:
array=np.random.randn(3,4)
array

array([[ 0.11647733, -0.40937112, -0.34339336,  0.22064762],
       [ 0.59558965,  0.40698352,  0.33038507, -0.82172662],
       [-0.38704777, -0.40208458,  1.64867673,  0.50485753]])

In [36]:
np.round(array,decimals=2)

array([[ 0.12, -0.41, -0.34,  0.22],
       [ 0.6 ,  0.41,  0.33, -0.82],
       [-0.39, -0.4 ,  1.65,  0.5 ]])

In [37]:
sports=np.array(['golf','cricket','fball','cricket'])
np.unique(sports)

array(['cricket', 'fball', 'golf'],
      dtype='<U7')

### pandas

In [39]:
import pandas as pd
import numpy as np

In [48]:
labels=['a','b','c','d']
sample_list=[100,200,300,400]
array=np.array(['one','two','three','four'])
dict={'a':10,'b':20,'c':30,'d':40}

In [49]:
pd.Series(data=sample_list)

0    100
1    200
2    300
3    400
dtype: int64

In [50]:
pd.Series(data=sample_list,index=array)

one      100
two      200
three    300
four     400
dtype: int64

In [53]:
pd.Series(labels,array)

one      a
two      b
three    c
four     d
dtype: object

In [55]:
pd.Series(dict)

a    10
b    20
c    30
d    40
dtype: int64

In [56]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','baseball'])
sports1

cricket       1
football      2
basketball    3
baseball      4
dtype: int64

In [57]:
sports1['basketball']

3

In [59]:
sports1[3] #also access by indexing

4

In [60]:
sports2=pd.Series([11,2,3,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football     2
baseball     3
golf         4
dtype: int64

In [61]:
sports1+sports2

baseball       7.0
basketball     NaN
cricket       12.0
football       4.0
golf           NaN
dtype: float64

In [69]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H '.split(),columns='score1 score2 score3 score4 score5 '.split())
df1

score1    score2    score3    score4    score5
A  0.050058  0.023957  0.668579  0.044240  0.471439
B  0.580449  0.702921  0.982811  0.606487  0.943057
C  0.276341  0.710025  0.568767  0.388482  0.790082
D  0.299161  0.465751  0.221246  0.945341  0.470587
E  0.379936  0.337048  0.053556  0.080363  0.915364
F  0.889005  0.632679  0.012710  0.726117  0.475393
G  0.780088  0.770625  0.951311  0.084288  0.492087
H  0.400584  0.283507  0.507209  0.546962  0.511441

In [70]:
df1['score1']

A    0.050058
B    0.580449
C    0.276341
D    0.299161
E    0.379936
F    0.889005
G    0.780088
H    0.400584
Name: score1, dtype: float64

In [71]:
df1[["score1","score2","score3"]]

score1    score2    score3
A  0.050058  0.023957  0.668579
B  0.580449  0.702921  0.982811
C  0.276341  0.710025  0.568767
D  0.299161  0.465751  0.221246
E  0.379936  0.337048  0.053556
F  0.889005  0.632679  0.012710
G  0.780088  0.770625  0.951311
H  0.400584  0.283507  0.507209

In [72]:
df1["score6"]=df1["score1"]+df1["score2"]
df1

score1    score2    score3    score4    score5    score6
A  0.050058  0.023957  0.668579  0.044240  0.471439  0.074015
B  0.580449  0.702921  0.982811  0.606487  0.943057  1.283370
C  0.276341  0.710025  0.568767  0.388482  0.790082  0.986366
D  0.299161  0.465751  0.221246  0.945341  0.470587  0.764911
E  0.379936  0.337048  0.053556  0.080363  0.915364  0.716983
F  0.889005  0.632679  0.012710  0.726117  0.475393  1.521684
G  0.780088  0.770625  0.951311  0.084288  0.492087  1.550713
H  0.400584  0.283507  0.507209  0.546962  0.511441  0.684090

In [75]:
df2={'ID':['101','102','103','107','176'],'name':["bhavy","garima","sushma","taksh","shalu"],"profit":[20,30,40,50,60]}
df=pd.DataFrame(df2)
df

ID    name  profit
0  101   bhavy      20
1  102  garima      30
2  103  sushma      40
3  107   taksh      50
4  176   shalu      60

In [76]:
df["ID"]

0    101
1    102
2    103
3    107
4    176
Name: ID, dtype: object

In [78]:
df[["ID","name"]]

ID    name
0  101   bhavy
1  102  garima
2  103  sushma
3  107   taksh
4  176   shalu

In [79]:
df=df.drop("ID",axis=1)
df

name  profit
0   bhavy      20
1  garima      30
2  sushma      40
3   taksh      50
4   shalu      60

In [80]:
df.drop(3)

name  profit
0   bhavy      20
1  garima      30
2  sushma      40
4   shalu      60